language: node_js
node_js:
- '8'
env:
  matrix:
  - SERVICE=frontend
  - SERVICE=api
  - SERVICE=integration
  global:
  - secure: Jk996bhUNbf5uoK/Pxnig2jM+Siw/yZIo09QGiXbgdXWxgjRZLjkBKSyx/aXGWuMJFm32Fwnqdz6fb6PqT7kVFL4Uk+294ZnCY7k+qd8LsPARNg5/WmZA/NgQugF4xTdxFuldyNJWnS0jKbmUtNM9eh9TQEGJBe6UvgBdXq3f4DNsPfpEbfMVCoQgD67YeDfY4DP/aEKTQcekgMer90bQ4jmnXhpgmy3cdY1/gmXShu73HCB5giNqRCbsQ2Tc3rP4wumDVXqzsFA46lktSjtWqcVM2wznYrc0A7z5b4FxJaACwx/iWnXdFHwrUxqPP77CJaVlzFzp73bDbLg+j43YoF4l0Jl5txpsf8J++ymd/6KDPjzFtzRe/176Jdsqhipzjo1LV4HDuXIFNpXKy5kwDX0EvIWXEqoFUNL74VjwigzuUhG+/6Oczpix5eNvvUqYUMFbDFiGFBmepZ6t11GiZek1NjZoYOK2+lr7KT+cRpxScZ1t2kFQphM1OpgaOw+vuAC2FnZMURo3nOXOLqLuMIO0XV5W9bhZ5kV7NDrVXbNl072bXbjWQ8MLEs3sNGlK7vt4v0anCej6PPbp7YskKRrylhojGeh6EPDzWcfg+WUl62K2G6h8HYgUuegZnch/Q8s6lc1A40+EMgoFR54+5xVy5Qa+WsPVC2d6n9n+e4=
  - secure: qWjeS87UifmbRYFRqRAUsAKF4T/W0IJos3/VfS84U1FiLiLlejfrWPnZoZGhaW1+Fy+5fzMN2sNTKXhjodUm+pVj60OAuzq+zcYA6DayJsgF16zlZVCnlHJOCFu9wql3rJ2SH1A8Zz/yOi1WG+7rX8sDPvVo+GVUDae8ojMDDHdhx+PfgWK5sdymOa81o90tK8DEOQoTVoCDlKTmUlUItYvr1qeAvHN/Ag3fUCMFc70MxZpQwsIScp7/Hm2GFOPk7tV7SmhPYtBz6oK46uH8JyGwzb+bTR8h+xOEZ++Fq4cGt9UwUyzmiQO8KeYp533TXPAU19pXQspP9yL3YVQRxOtyh9XCCLuZdcjStxI5MSELw9aYQAfqCA/JQp/MGzmeDJSZmkVHoeQDVKeJkp6FVykZBWwJ14YzEUrKoyOQLNWDhJJ0P8ISijn2jLo+Uebx2qk4Yr5yZrjUPCPTms0r0rfSzEXJ0jjucJRzNX9mGGs2rGG1HpJUY3kJlpGUSO29J5TzwdeKfce9UKaUPMGtEZFOZGqtr/KDFJVf13XHRsLKgDf2FY+LPjQoSyeNnGuvCELBZt8XZACapc5JjGxIbnEU0J3UJFxlHxmySzY35ubt6gSGebRnDhvHKXedxtMCdd7O7tu/LOXoDkUvTCa/phiDQiscY6wzRZtJ+yxZRfo=
cache: yarn
install: ci/install.sh
script: ci/script.sh
addons:
  browserstack:
    username: $BROWSER_STACK_USER
    access_key:
      secure: $BROWSER_STACK_ACCESS_KEY
    force_local: true
    only: localhost,8080,0
